#download reference genome, make sure star, bedtools is installed (e.g., conda install -c bioconda star, conda install -c bioconda bedops)
# 2.7.3a is used for zUMI per default - therefore also sintalling that version
cd GRCh38
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh38.primary_assembly.genome.fa.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.annotation.gtf.gz
gunzip *.gz
STAR --runThreadN 70 \
     --runMode genomeGenerate \
     --genomeDir GRCh38_STAR_index \
     --genomeFastaFiles GRCh38.primary_assembly.genome.fa \
     --sjdbGTFfile gencode.v43.annotation.gtf \
     --sjdbOverhang 73

#STAR only gives chromosome location: we can annotate those location with bedtools (but it needs a bed file and not gtf)
#therefore 1.) transform gtf into bed
# name the feature here, we filter only columns with this faeture!!
gtf2bed --attribute-key=gene_name < data/GRCh38/gencode.v43.annotation.gtf > data/GRCh38/genes.bed
#filter out chromosome region plus the feature
cut -f1-4 data/GRCh38/genes.bed | sort -u > data/GRCh38/genesFiltered.bed
#make a simple bed file of chr start end transcript for ezgi
awk '{match($0, /gene_id "([^"]+)"/, arr); print $1"\t"$2"\t"$3"\t"arr[1];}' ./data/GRCh38/genes.bed > ./data/GRCh38/genes_simple.bed

#download HELA data of SIGNAL-seq (multimodal data for RNA&protein generated by combinatorial indexing)
cd ../data
wget "https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR28056729/SRR28056729" -O SIGNALseq/SRR28056729.sra
wget "https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR28056728/SRR28056728" -O SIGNALseq/SRR28056728.sra
cd SIGNALseq
fastq-dump --split-files --gzip SIGNALseq/SRR28056729.sra
fastq-dump --split-files --gzip SIGNALseq/SRR28056728.sra
#then, bcs zUMI can not handle read names that do not follow standard illumina style, we need to remove the length information from the headers
zcat ./raw/SRR28056729_1.fastq.gz | sed '1~4 s/ length=74//' | gzip > ../SIGNALseq/raw/SRR28056729_1b.fastq.gz
zcat ./raw/SRR28056729_2.fastq.gz | sed '1~4 s/ length=86//' | gzip > ../SIGNALseq/raw/SRR28056729_2b.fastq.gz

zcat ./raw/SRR28056729_1b.fastq.gz | awk 'NR%4==3{$0="+"}1' | pigz > ./SIGNALseq/raw/SRR28056729_1c.fastq.gz
zcat ./raw/SRR28056729_2b.fastq.gz | awk 'NR%4==3{$0="+"}1' | pigz > ./SIGNALseq/raw/SRR28056729_2c.fastq.gz

#download the SHENDURE data (sciRNA-seq)
# a combinatorial single-cell nucleus technique
cd ../data
wget "https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR16635352/SRR16635352" -O sciRNAseq/SRR16635352.sra
cd ../sciRNAseq
fastq-dump --split-files --gzip sciRNAseq/SRR16635352.sra

# processed single-cell RNA/ protein data for the hela dataset can be downloaded here: https://zenodo.org/records/10676523
# background data to run zUMI on the SIGNALseq data (with GENCODE reference) was downloaded from https://github.com/TAPE-Lab/SIGNAL-seq/tree/main/figure_1_hela/00_preprocessing_rna 
# into ./SIGNALseq_Analysis/zUMIs_analysis/


# download xDBiT (spatial single-cell data with x&y coordinate barcodes)
# SRR20073555